# Generated by Django 6.1 on 2026-08-17 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_branch_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('seat_count', models.PositiveIntegerField()),
                ('doors', models.PositiveIntegerField()),
                ('luggage_capacity', models.PositiveIntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('segment', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('sport', 'Sport'), ('luxury', 'Luxury')], max_length=50)),
                ('body_type', models.CharField(choices=[('economic', 'Economik'), ('standard', 'Standart'), ('premium', 'Premium'), ('luxury', 'Lüks')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('identity_number', models.CharField(max_length=20, unique=True)),
                ('license_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('km', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Müsait'), ('rented', 'Kirada'), ('maintenance', 'Bakımda'), ('transfer', 'Transferde')], default='available', max_length=50)),
                ('current_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.branch')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Personel'), ('manager', 'Yönetici')], default='staff', max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('active', 'Aktif'), ('cancelled', 'İptal Edildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.customer')),
                ('dropoff_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_reservations', to='main.branch')),
                ('pickup_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_reservations', to='main.branch')),
            ],
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_km', models.PositiveIntegerField()),
                ('return_km', models.PositiveIntegerField(blank=True, null=True)),
                ('damage_notes', models.TextField(blank=True)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.reservation')),
            ],
        ),
    ]
